#include <iostream>

using namespace std;
/*  SE TIENE QUE INGRESAR UN NUMERO, ESTE SE TIENE QUE VALIDAR QUE SOLO SEA PAR O DIVISIBLE ENTRE 5
DEBERA DE CONTAR CUANTOS SON PARES Y CUANTOS SON DIVISIBLES ENTRE 5. TIENE QUE PREGUNTAR SI DESEA CONTINUAR
,VALIDAR QUE LA RESPUESTA SOLO SEA N O S. OBTENER EL NUMERO MAYOR DE LOS NUMEROS QUE SE INGRESARON CORRECTAMNETE.
OBTENER EL PROMEDIO DE LOS NUMEROS QUE FUERON MAYORES A 100. DESARROLLAR EL PROGRAMA USANDO USANDO CICLO WHILE,
ESTRUCTURAS DE CONDICION.
SE TOMARA EN CUENTA EL ORDEN, IDENTADO, EL NOMBRE DE LAS VARIABLES Y LA EFICIENCIA DEL PROGRAMA.
SUBIR EL PROYECTO SOLO EL MAIN. */

int main()
{
    cout << "Hello world!" << endl;
    return 0;
}
